name: Збірка і деплой

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Отримати код
      uses: actions/checkout@v4

    - name: Логін у ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Зібрати і пуш образів
      run: |
        for service in vote result worker; do
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/$service:latest ./$service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/$service:latest
        done

    - name: Оновити compose файл
      run: |
        # Ми замінюємо рядок 'build: ./сервіс' на рядок 'image: адреса_реєстру/сервіс:latest'
        # Це гарантує, що у кожного сервісу буде вказано образ для завантаження
        for service in vote result worker; do
          sed -i "s|build: .\/$service|image: ${{ secrets.ACR_LOGIN_SERVER }}/$service:latest|g" docker-compose.yml
        done

    - name: Копіювання compose на VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "docker-compose.yml"
        target: "app/"

    - name: Деплой через SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          mkdir -p app && cd app
          # Логінимося в ACR на самій VM, щоб вона могла завантажити (pull) приватні образи
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" | sudo docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin
          sudo docker compose pull
          sudo docker compose up -d --remove-orphans
          sudo docker compose ps
